"""Convert the GRE Vocab Handbook .docx into data.js for the website.

Usage:  python tools/convert_docx.py [path/to/handbook.docx] [output data.js]

Expected document layout:
  Heading 1  -> "Day N"
  Heading 2  -> "Cluster #N — Cluster name"
  Table      -> columns: Word | Meaning | Mnemonic (first row is the header)
"""
import json
import re
import sys
from pathlib import Path

import docx
from docx.oxml.ns import qn
from docx.table import Table
from docx.text.paragraph import Paragraph

ROOT = Path(__file__).resolve().parent.parent
SRC = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "source" / "GRE_Vocab_Handbook.docx"
OUT = Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "data.js"

CLUSTER_RE = re.compile(r"Cluster\s*#\s*(\d+)\s*[—–-]\s*(.+)", re.I)
DAY_RE = re.compile(r"Day\s*(\d+)", re.I)


def convert(src: Path) -> dict:
    d = docx.Document(str(src))
    days, clusters = [], []
    cur_day = cur_cluster = None
    for child in d.element.body.iterchildren():
        if child.tag == qn("w:p"):
            p = Paragraph(child, d)
            text = p.text.strip()
            if not text:
                continue
            style = p.style.name if p.style is not None else ""
            if style == "Heading 1":
                m = DAY_RE.search(text)
                cur_day = {"day": int(m.group(1)) if m else len(days) + 1, "title": text, "clusters": []}
                days.append(cur_day)
            elif style == "Heading 2":
                m = CLUSTER_RE.search(text)
                cid = int(m.group(1)) if m else len(clusters) + 1
                name = m.group(2).strip() if m else text
                cur_cluster = {"id": cid, "name": name, "day": cur_day["day"] if cur_day else None, "entries": []}
                clusters.append(cur_cluster)
                if cur_day:
                    cur_day["clusters"].append(cid)
        elif child.tag == qn("w:tbl") and cur_cluster is not None:
            t = Table(child, d)
            rows = [[c.text.strip() for c in r.cells] for r in t.rows]
            if rows and rows[0][0].lower() == "word":
                rows = rows[1:]
            for cells in rows:
                if len(cells) < 2 or not cells[0]:
                    continue
                cells += [""] * (3 - len(cells))
                cur_cluster["entries"].append({"word": cells[0], "meaning": cells[1], "mnemonic": cells[2]})
    return {"title": "GRE Vocabulary Handbook", "days": days, "clusters": clusters}


def main():
    data = convert(SRC)
    n_words = sum(len(c["entries"]) for c in data["clusters"])
    js = "// Generated by tools/convert_docx.py — do not edit by hand.\n"
    js += "window.GRE_DATA = " + json.dumps(data, ensure_ascii=False, indent=1) + ";\n"
    OUT.write_text(js, encoding="utf-8")
    print(f"{SRC.name}: {len(data['days'])} days, {len(data['clusters'])} clusters, {n_words} entries -> {OUT}")


if __name__ == "__main__":
    main()
